name: Github Actions Demo
on: 
  push:
    branches:
      - main
    path-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
   - cron: '15 6 * * 0'
   workflow_dispatch:
jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
    - run: |
      echo "The jobs was trigrerred by Event from Anshul: ${{ gitub.event_name }}"
      echo "THe name of branch is ${{ github.ref }}"
    - run: tree -a
    
